import fs from "fs";
import path from "path";

const ROOT = path.join(process.cwd(), "public/images/celebration-boards");
const OUT = path.join(process.cwd(), "src/data/celebrationBoardsManifest.ts");

function isImage(file) {
  return /\.(jpg|jpeg|png|webp)$/i.test(file);
}

function sortByFilename(a, b) {
  return a.localeCompare(b, undefined, { numeric: true });
}

function titleFromSlug(slug) {
  const parts = slug.split("-");
  const date = parts.slice(0, 3).join("-");
  const title = parts
    .slice(3)
    .join(" ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  return { date, title };
}

function main() {
  if (!fs.existsSync(ROOT)) return;

  const boardDirs = fs
    .readdirSync(ROOT, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .reverse();

  const boards = boardDirs.map((slug) => {
    const dirPath = path.join(ROOT, slug);

    // 1) image files
    const files = fs.readdirSync(dirPath).filter(isImage).sort(sortByFilename);

    // 2) optional meta.json
    const metaPath = path.join(dirPath, "meta.json");
    let meta = null;

    if (fs.existsSync(metaPath)) {
      try {
        meta = JSON.parse(fs.readFileSync(metaPath, "utf8"));
      } catch (e) {
        console.warn(`⚠️ Could not parse meta.json for ${slug}`);
      }
    }

    // 3) fallbacks from folder slug
    const { date, title: fallbackTitle } = titleFromSlug(slug);

    // 4) final fields (meta overrides fallback)
    const title = meta?.title || fallbackTitle;
    const header = meta?.header || "Celebration Board";
    const description = meta?.description || "";
    const captions = meta?.captions || {};

    return {
      slug,
      date,
      title,
      header,
      description,
      images: files.map((file) => ({
        src: `/images/celebration-boards/${slug}/${file}`,
        caption: captions[file] || "",
      })),
    };
  });

  const content = `// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by scripts/generateCelebrationBoardsManifest.mjs


export const celebrationBoards = ${JSON.stringify(boards, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, content);

  console.log("✅ Celebration boards manifest generated.");
}

main();
