// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by scripts/generateCelebrationBoardsManifest.mjs


export const celebrationBoards = [
  {
    "slug": "2026-02-27-celebrations-board",
    "date": "2026-02-27",
    "title": "Celebrations Board",
    "header": "Celebration Board",
    "description": "",
    "images": []
  },
  {
    "slug": "2025-11-12-czech-biscuits",
    "date": "2025-11-12",
    "title": "Czech Biscuits",
    "header": "Celebration Board",
    "description": "",
    "images": [
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1003.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1004.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1005.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1034.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1035.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1036.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1037.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1039.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1040.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1042.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1043.jpg",
        "caption": ""
      },
      {
        "src": "/images/celebration-boards/2025-11-12-czech-biscuits/100_1044.jpg",
        "caption": ""
      }
    ]
  }
];
